### ISSUE TITLE
The number of directories under repos/ is far too long 

### ISSUE THREAD

**Issue by boopathi** [porter-io/tag-github#4]
As discussed on HN,

https://news.ycombinator.com/item?id=9315247

Can we have them arranged alphabetically ? 26 entries or 26*26 (aa-zz) entires ? maybe ?

But I fear one particular element would be very much populated ? like repos like angular-, or rails-\* or react-*. But still, this would at least be better than having the entire list in a single directory.

**Comment by ledzep2** [comment]
The repos are arranged as repos/owner/name for now. There are a lot of duplicate repo names so we can't directly use them as directory names. 

Making the dataset Github UI friendly is nice to have for sure. However the data set itself isn't meant to be explored with just Github UI. And in my opinion it's not more human-friendly to have deeper directories. So if we were gonna split them up into sub-directories, it would be for performance reasons.

**Comment by boopathi** [comment]
Repos like cdnjs, jsdelivr have this problem too and they don't minimize the number of items in the directory. So I guess it's safe to assume that it's not that important of a concern and only if it's really necessary for us to navigate code through Github, this makes sense. We can make a call and close this.

**Comment by ledzep2** [comment]
Yes. You are right. Thank you for your suggestions. I'm closing this and we will always welcome suggestions for better structure design.
